# Week 1 - Basic Data Exploration and Cleaning using Pandas

## Objective
To perform data exploration and cleaning on the Shopping Dataset using Pandas.

In [2]:
import pandas as pd
import glob
import os

## Dataset Discovery

The dataset consists of multiple CSV files. The glob module is used to automatically identify all CSV files present in the dataset directory.

In [3]:
files = glob.glob("../data/*.csv")

print("Total CSV files found:", len(files))

Total CSV files found: 98

## Dataset Inspection

Before combining all CSV files, a sample dataset was inspected to understand the schema and verify consistency across files.

In [4]:
sample_df = pd.read_csv(files[0])

sample_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [5]:
sample_df.shape

(4, 24)

In [6]:
sample_df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [7]:
sample_df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said       float64
seller_name               float64
sizes                         str
videos                        str
seller_information        float64
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

## Schema Validation

Before combining all datasets, the column structure of each CSV file was validated to ensure consistency.

In [8]:
column_counts = []

for file in files:
    df = pd.read_csv(file)
    column_counts.append(len(df.columns))

print("Unique column counts:", set(column_counts))

Unique column counts: {24}

In [9]:
first_columns = list(pd.read_csv(files[0]).columns)

all_same = True

for file in files[1:]:
    current_columns = list(pd.read_csv(file).columns)

    if current_columns != first_columns:
        all_same = False
        print(f"Column mismatch found in {file}")
        break

print("All files have same columns:", all_same)

All files have same columns: True

## Dataset Integration

After validating schema consistency across all CSV files, the datasets were combined into a single DataFrame using Pandas.

In [10]:
all_dfs = []

for file in files:
    df = pd.read_csv(file)
    all_dfs.append(df)

combined_df = pd.concat(all_dfs, ignore_index=True)

In [11]:
combined_df.shape

(2000, 24)

In [12]:
combined_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [13]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2000 non-null   int64
 1   title                   2000 non-null   str
 2   product_description     2000 non-null   str
 3   rating                  2000 non-null   float64
 4   ratings_count           2000 non-null   int64
 5   initial_price           2000 non-null   float64
 6   discount                1758 non-null   float64
 7   final_price             2000 non-null   str
 8   currency                2000 non-null   str
 9   images                  2000 non-null   str
 10  delivery_options        2000 non-null   str
 11  product_details         2000 non-null   str
 12  breadcrumbs             2000 non-null   str
 13  product_specifications  2000 non-null   str
 14  amount_of_stars         2000 non-null   str
 15  what_customers_said     854 non-null    object
 16  seller_name             1398 non-null   object
 17  sizes                   2000 non-null   str
 18  videos                  438 non-null    object
 19  seller_information      1398 non-null   object
 20  variations              876 non-null    object
 21  best_offer              2000 non-null   str
 22  more_offers             2000 non-null   str
 23  category                2000 non-null   str
dtypes: float64(3), int64(2), object(5), str(14)
memory usage: 375.1+ KB

## Handling Missing Values

The combined dataset was checked for missing values to identify incomplete records and determine appropriate cleaning steps.

In [19]:
combined_df.isnull().sum()

product_id                   0
title                        0
product_description          0
rating                       0
ratings_count                0
initial_price                0
discount                   242
final_price                  0
currency                     0
images                       0
delivery_options             0
product_details              0
breadcrumbs                  0
product_specifications       0
amount_of_stars              0
what_customers_said       1146
seller_name                602
sizes                        0
videos                    1562
seller_information         602
variations                1124
best_offer                   0
more_offers                  0
category                     0
dtype: int64

In [20]:
missing_values = combined_df.isnull().sum()

missing_values[missing_values > 0]

discount                242
what_customers_said    1146
seller_name             602
videos                 1562
seller_information      602
variations             1124
dtype: int64

The dataset contains missing values in a few columns. These columns were identified before applying suitable data cleaning techniques.

In [23]:
object_cols = combined_df.select_dtypes(include="object").columns

combined_df[object_cols] = combined_df[object_cols].fillna("Unknown")

C:\Users\malli\AppData\Local\Temp\ipykernel_5044\1977781753.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = combined_df.select_dtypes(include="object").columns

In [22]:
numeric_cols = combined_df.select_dtypes(include=["int64", "float64"]).columns

combined_df[numeric_cols] = combined_df[numeric_cols].fillna(0)

In [24]:
combined_df.isnull().sum().sum()

np.int64(0)

Missing values in categorical columns were replaced with "Unknown", while missing values in numerical columns were replaced with 0. After cleaning, no missing values remained in the dataset.